baseURL = 'https://venushotyoga.hr'
languageCode = 'hr'
title = 'Najbolja yoga Zagreb - ako tražite yoga usluge ili pomlađivanje - Venus hot yoga je mjesto za tebe'
defaultContentLanguage = 'hr'

enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

[services]
  [services.googleAnalytics]
    ID = 'G-WV6G3SGDB2'

[languages]
  [languages.hr]
    languageName = 'HR'
    languageCode = 'hr'
    contentDir = 'content/hr'
    weight = 1
    [languages.hr.params]
      LanguageEmoji = "images/svg/flag-for-croatia.svg"
  [languages.en]
    languageName = 'EN'
    languageCode = 'en'
    contentDir = 'content/en'
    weight = 2
    [languages.en.params]
      LanguageEmoji = "images/svg/flag-for-united-states.svg"

[frontmatter]
  date = ['date', 'publishDate', 'pubdate', 'lastmod', 'modified']
  expiryDate = ['expiryDate', 'unpublishdate']
  lastmod = [':git', 'lastmod', 'modified', 'date', 'publishDate', 'pubdate']
  publishDate = ['publishDate', 'pubdate', 'date']

[sitemap]
  disable = false

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [module.hugoVersion]
    extended = false
    min      = "0.152.2"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'
  [[module.mounts]]
    source = 'static/images'
    target = 'assets/images'
  [[module.mounts]]
    source = "node_modules/alpine-turbo-drive-adapter/dist"
    target = "assets/js/libs/alpinejs-turbolinks"
  [[module.mounts]]
    source = "node_modules/alpinejs/dist"
    target = "assets/js/libs/alpinejs"

# Set markup.goldmark.parser.wrapStandAloneImageWithinParagraph = false so standalone images will not be wrapped in <p>>/p> tags. Also set block = true to support attributes on block elements:
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # Allow HTML in md files
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true