baseURL = 'http://venushotyoga.hr/'
languageCode = 'hr'
title = 'Venus Hot Yoga'

[taxonomies]
  series = 'series'

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"

[[menu.main]]
identifier = "products"
name = "Products"
url = "/products/"

[[menu.main]]
parent = "products"
weight = 20
  [menu.main.params]
  divider = true