baseURL = 'http://venushotyoga.hr/'
languageCode = 'hr'
title = 'Venus Hot Yoga'

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 20