baseURL = 'http://venushotyoga.hr/'
languageCode = 'hr'
title = 'Venus Hot Yoga'

enableRobotsTXT = true
enableGitInfo = true

[sitemap]
changefreq = 'monthly'
filename = 'sitemap.xml'
priority = 0.5

[server]
[[server.headers]]
for = '/**'
[server.headers.values]
Referrer-Policy = 'strict-origin-when-cross-origin'
X-Content-Type-Options = 'nosniff'
X-Frame-Options = 'DENY'
X-XSS-Protection = '1; mode=block'