# when using the default proxy server port
local_backend: true

backend:
  name: git-gateway
  branch: master

site_url: https://venushotyoga.netlify.app

media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "/images"

collections: # A list of collections the CMS should be able to edit
  - name: "posts" # Used in routes, e.g., /admin/collections/post
    label: "Posts" # Used in the UI
    label_singular: 'Blog' # Used in the UI, ie: "New Post"
    description: >
      Kreiraj novi blog.
    folder: "content/posts" # The path to the folder where the documents are stored
    path: "{{slug}}/index"
    summary: '{{title}} -- {{day}}/{{month}}/{{year}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: 'Tags', name: 'tags', widget: 'select', options: ['Beginners', 'Lifestyle', 'Strength', 'Meditation', 'Philosophy', 'Flexibility', 'Stress Relief'], multiple: true}
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image", media_folder: "/static/images"}
      - { label: "Body", name: "body", widget: "markdown" }
  


  - name: "pages"
    label: "Pages"
    files:
      - file: 'content/faq.md' # Used in routes, e.g., /admin/collections/:slug/edit
        label: 'FAQ Page' # Used in the UI
        name: 'faq' # The path to the folder where the documents are stored
        fields:
          - label: 'Frequently Asked Questions'
            name: 'faq'
            widget: 'list'
            collapsed: true
            fields:
              - label: 'Question'
                name: 'question'
                widget: 'string'
              - label: 'Answer'
                name: 'answer'
                widget: 'markdown'

      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Blurb", name: "blurb", widget: "markdown" }
          - {
              label: "Section",
              name: "section",
              widget: "object",
              fields:
                [
                  { label: "Heading", name: "heading", widget: string },
                  { label: "Text", name: "text", widget: "markdown" },
                ],
            }
      
      - file: "content/about.md"
        label: "About Page"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - file: "content/contact.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: 'Map', name: 'map', widget: 'map' }
      
  - name: "Prices & Schedule"
    label: "Prices & Schedule"
    files:
      - file: "content/rejuvenation.md"
        label: "Change Price for LPG"
        name: Services
        fields:
          - label: Services
            name: services
            collapsed: true
            widget: list
            fields:
            - label: Category
              name: category
              collapsed: true
              widget: list
            - label: Prices
              name: prices
              collapsed: true
              widget: list
              fields: 
                - label: Service
                  name: service
                  widget: string
                - label: Price
                  name: price
                  widget: string

      - file: "content/hot-yoga.md"
        label: "Change Price & Schedule for Yoga"
        name: yoga
        fields:
          - label: Prices
            name: prices
            collapsed: true
            widget: list
            fields: 
              - label: Service
                name: service
                widget: string
              - label: Price
                name: price
                widget: string

          - label: Raspored
            name: raspored
            collapsed: true
            widget: list
            fields:
            - label: Start Time
              name: startTime
              widget: string
            - label: Termin
              name: termin
              collapsed: true
              widget: list
              fields:
              - label: Dan
                name: dan
                widget: select
                options:
                - label: Ponedeljak
                  value: Ponedeljak
                - label: Utorak
                  value: Utorak
                - label: Srijeda
                  value: Srijeda
                - label: Četvrtak
                  value: Četvrtak
                - label: Petak
                  value: Petak
                - label: Subota
                  value: Subota
              - label: Usluga
                name: usluga
                widget: string
              - label: Start Time
                name: startTime
                widget: string
                hint: "The start time of the previous entry: (Start Time) must be the same"
              - label: EndTime
                name: endTime
                widget: string
              - label: Opis
                name: opis
                widget: string