# when using the default proxy server port: npx decap-server
local_backend: true
site_url: https://venushotyoga.netlify.app
media_folder: "/static/images" # Folder where user uploaded files should go
public_folder: "/images"
backend:
  name: git-gateway
  branch: main

collections: # A list of collections the CMS should be able to edit
  - name: "posts" # Used in routes, e.g., /admin/collections/post
    label: "Posts" # Used in the UI
    label_singular: 'Blog' # Used in the UI, ie: "New Post"
    folder: "content/hr/posts" # The path to the folder where the documents are stored
    path: "{{slug}}/index"
    summary: '{{title}} -- {{day}}/{{month}}/{{year}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: 'Tags', name: 'tags', widget: 'select', options: ['Beginners', 'Lifestyle', 'Strength', 'Meditation', 'Philosophy', 'Flexibility', 'Stress Relief'], multiple: true}
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image", media_folder: "/static/images"}
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    files:
      - file: 'content/hr/faq.md'
        label: 'FAQ Page'
        name: 'faq'
        fields:
          - { label: 'Frequently Asked Questions',  name: 'faq', widget: 'list', collapsed: true,
                fields:
                  [ 
                    { label: 'Question', name: 'question', widget: 'string' },
                    { label: 'Answer', name: 'answer', widget: 'markdown' }
                  ]
            }
      - file: "content/hr/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Blurb", name: "blurb", widget: "markdown" }
          - { label: "Section", name: "section", widget: "object",
              fields: [
                { label: "Heading", name: "heading", widget: string },
                { label: "Text", name: "text", widget: "markdown" },
              ],
            }
  - name: "Prices & Schedule"
    label: "Prices & Schedule"
    files:
      - file: "content/hr/pricing.md"
        label: "Change Pricing"
        name: Services
        fields:
          - { label: Hotyoga, name: hotyoga, collapsed: true, widget: list,
              fields: [
                { label: Category, name: category, collapsed: true, widget: list },
                { label: Prices, name: prices, collapsed: true, widget: list,
                  fields: [
                    { label: Service, name: service, widget: string },
                    { label: Price, name: price, widget: string }
                  ]
                }
              ]
            }
          - { label: Rejuvenation, name: rejuvenation, collapsed: true, widget: list,
              fields: [
                { label: Category, name: category, collapsed: true, widget: list },
                { label: Prices, name: prices, collapsed: true, widget: list,
                  fields: [
                    { label: Service, name: service, widget: string },
                    { label: Price, name: price, widget: string }
                  ]
                }
              ]
            }
      - file: "content/hr/hot-yoga.md"
        label: "Change Schedule"
        name: yoga
        fields:
          - { label: Schedule, name: schedule, collapsed: true, widget: list,
              fields: [
                { label: Day, name: day, collapsed: true, widget: list },
                { label: Appointments, name: appointments, collapsed: true, widget: list,
                  fields: [
                    { label: service, name: service, collapsed: true, widget: string },
                    { label: startTime, name: startTime, collapsed: true, widget: string },
                    { label: endTime, name: endTime, collapsed: true, widget: string },
                    { label: description, name: description, collapsed: true, widget: string },
                  ]
                },
              ]
            }