backend:
  name: git-gateway
  local_backend: true
  branch: prod
media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "images"
collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/post
    label: "Posts" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    path: "{{slug}}/index"
    media_folder: "" # Save images in the post's own folder instead of the static folder
    public_folder: ""
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Blurb", name: "blurb", widget: "text" }
          - {
              label: "Section",
              name: "section",
              widget: "object",
              fields:
                [
                  { label: "Heading", name: "heading", widget: string },
                  { label: "Text", name: "text", widget: "text" },
                ],
            }
      - file: "content/about/index.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "text" }
      - file: "content/schedule/_index.md"
        label: Schedule
        name: schedule
        fields:
        - label: Raspored
          name: raspored
          collapsed: true
          widget: list
          fields:
          - label: Start Time
            name: startTime
            widget: string
          - label: Termin
            name: termin
            collapsed: true
            widget: list
            fields:
            - label: Dan
              name: dan
              widget: select
              options:
              - label: Ponedeljak
                value: Ponedeljak
              - label: Utorak
                value: Utorak
              - label: Srijeda
                value: Srijeda
              - label: Četvrtak
                value: Četvrtak
              - label: Petak
                value: Petak
              - label: Subota
                value: Subota
            - label: Usluga
              name: usluga
              widget: string
            - label: StartTime
              name: startTime
              widget: string
            - label: EndTime
              name: endTime
              widget: string
            - label: Opis
              name: opis
              widget: string